# Generated by Django 2.2.12 on 2020-04-23 13:44

from django.db import migrations, models
import django.db.models.deletion
import user_admin.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.FloatField(default=0)),
                ('isCheckout', models.BooleanField(default=False)),
                ('cart_orderlines', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=200, unique=True)),
                ('isAvtive', models.BooleanField(default=True)),
                ('Image', models.ImageField(default='Categorys/2426188-200.png', upload_to='Categorys')),
            ],
        ),
        migrations.CreateModel(
            name='PackgeSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('final_price', models.FloatField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Weight', models.FloatField()),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('Image', models.ImageField(default='Products/product-icon-png-2.png', upload_to='Products')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_admin.Category')),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAndDiscountMemberShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.Product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('typ', models.CharField(default='customer', max_length=200)),
            ],
            options={
                'ordering': ['typ'],
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('discount_percent', user_admin.fields.IntegerRangeField()),
                ('products', models.ManyToManyField(through='user_admin.ProductAndDiscountMemberShip', to='user_admin.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAndPackgeMemberShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.PackgeSale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.Product')),
            ],
        ),
        migrations.AddField(
            model_name='productanddiscountmembership',
            name='product_discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.ProductDiscount'),
        ),
        migrations.AddField(
            model_name='packgesale',
            name='products',
            field=models.ManyToManyField(through='user_admin.ProductAndPackgeMemberShip', to='user_admin.Product'),
        ),
        migrations.CreateModel(
            name='Order_Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('CartId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_admin.Cart')),
                ('ProductID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_admin.Product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='User_em',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.User'),
        ),
    ]
