# Generated by Django 3.0.4 on 2020-04-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCheckout', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=200, unique=True)),
                ('isAvtive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('typ', models.CharField(default='customer', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Weight', models.FloatField()),
                ('price', models.FloatField()),
                ('Quantity', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_admin.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('Quantity', models.IntegerField(default=1)),
                ('CartId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_admin.Cart')),
                ('ProductID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_admin.Product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='User_em',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.User'),
        ),
    ]
