# Generated by Django 3.0.4 on 2020-04-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='isAvtive',
            field=models.BooleanField(default=True),
        ),
    ]
