# Generated by Django 3.0.5 on 2020-04-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='typ',
            field=models.CharField(default='customer', max_length=200),
        ),
    ]
