# Generated by Django 3.0.5 on 2020-04-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_auto_20200406_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['typ']},
        ),
        migrations.AddField(
            model_name='cart',
            name='dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
