# Generated by Django 3.0.4 on 2020-04-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_remove_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
