# Generated by Django 3.0.5 on 2020-04-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_user_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_line',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
