# Generated by Django 3.0.4 on 2020-04-09 14:32

from django.db import migrations, models
import django.db.models.deletion
import user_admin.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_auto_20200406_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackgeSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('final_price', models.FloatField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductAndDiscountMemberShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('discount_percent', user_admin.fields.IntegerRangeField()),
                ('products', models.ManyToManyField(through='user_admin.ProductAndDiscountMemberShip', to='user_admin.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAndPackgeMemberShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.PackgeSale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.Product')),
            ],
        ),
        migrations.AddField(
            model_name='productanddiscountmembership',
            name='product_discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.ProductDiscount'),
        ),
        migrations.AddField(
            model_name='packgesale',
            name='products',
            field=models.ManyToManyField(through='user_admin.ProductAndPackgeMemberShip', to='user_admin.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='packge_sale',
            field=models.ManyToManyField(through='user_admin.ProductAndPackgeMemberShip', to='user_admin.PackgeSale'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_discout',
            field=models.ManyToManyField(through='user_admin.ProductAndDiscountMemberShip', to='user_admin.ProductDiscount'),
        ),
    ]
