# Generated by Django 3.0.5 on 2020-04-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0003_auto_20200409_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_line',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
