# Generated by Django 3.0.5 on 2020-04-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0003_auto_20200405_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_line',
            old_name='CardId',
            new_name='CartId',
        ),
    ]
