# Generated by Django 3.0.5 on 2020-04-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0004_order_line_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_line',
            name='total_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
