# Generated by Django 3.0.4 on 2020-04-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0005_auto_20200409_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['dt']},
        ),
    ]
